name: TrustedTeleport
main: cc.isotopestudio.TrustedTeleport.trustedteleport.TrustedTeleport

author: Mars
description: Teleport to a player directly with permission
website: http://isotopestudio.cc
version: 1.2.1
commands:
  tt:
    description: 传送到被信任的玩家
    usage: /<command>
    permission: TrustedTeleport.teleport
    permission-message: 你没有权限传送
    aliases: t
  ttp:
    description: 插件管理
    usage: /<command> help
    permission: TrustedTeleport.setting
    permission-message: 你没有权限设置传送
permission:
  TrustedTeleport.*:
    description: Allow to use this plugin
    default: op